### PR TITLE
fix string replacement routine behaviour in certain cases

### PR DESCRIPTION
**Pull request by moon-chilled**

### CODE REVIEW

**Comment by moon-chilled** [comment]
(Reported by byuu [here](https://twitter.com/byuu_san/status/1327884701671964672))

**Comment by Screwtapello** [comment]
(also [filed in higan-emu/nall](https://github.com/higan-emu/nall/issues/1))

**Comment by moon-chilled** [comment]
Should higan/ares/bsnes get nall/ruby/libco/hiro from git submodules?

(I think I proposed this at one point in the past, but forget the reception.  Certainly, duplication of effort doesn't seem like a great idea.)

**Comment by Screwtapello** [comment]
My intention (I'm a little busy right now, but I hope to get back to it) is to include nall/ruby/hiro into bsnes and higan with `git subtree`, as libco is now.

I was going to leave ares out of it, since I figured that's the emulator for people who want to stick closely to the code byuu/near originally released, but I'd merge a PR to ares:with-fixes that replaced libco with a subtree of the latest version, much as was done for higan and bsnes.

I [wrote up](https://zork.net/~st/jottings/extracting-libraries-with-git-subtree.html) the process I (intend to) follow, if you're interested.

**Pull request merged**
